export const surpriseMePrompts = [
    "Animal liberation activists freeing captive animals",
    "Vegan activists peacefully protesting for change",
    "Empowered individuals advocating for animal rights",
    "A powerful vegan demonstration in a bustling city",
    "Vegan activists using art to convey a powerful message",
    "Animal liberation march with banners and signs",
    "Compassionate activists rescuing animals from harm",
    "Vegan warriors fighting for a cruelty-free world",
    "A global movement for animal liberation",
    "Inspirational vegan leaders addressing a crowd",
    "Activists using social media to promote veganism",
    "Vegan protesters sharing plant-based facts",
    "Artistic murals advocating for animal rights",
    "Animal liberation activists engaging in civil disobedience",
    "Vegan outreach event spreading awareness",
    "Empathetic individuals rescuing animals from exploitation",
    "Activists creating positive change through education",
    "Vegan advocates speaking up for the voiceless",
    "A world transformed by vegan activism",
    "Animal rights activists promoting ethical choices",
    "Vegan influencers using their platforms for change",
    "Activists disrupting industries that harm animals",
    "A peaceful gathering advocating for vegan living",
    "Vegan activists collaborating for a common cause",
    "Empowered individuals organizing a vegan festival",
    "Animal liberation warriors breaking chains of oppression",
    "Vegan activists raising awareness in the community",
    "A global call for compassion and veganism",
    "Activists using technology to advance animal rights",
    "Vegan advocates inspiring others to join the movement",
    "Protesters demanding justice for animals",
    "Animal liberation activists promoting kindness over cruelty",
    "Vegan activists transforming the narrative on animal agriculture",
    "Activists creating impactful documentaries for change",
    "Vegan influencers promoting a plant-based lifestyle",
    "A wave of compassion sweeping the globe",
    "Animal rights advocates working towards legislative change",
    "Vegan activists organizing plant-powered fundraisers",
    "Activists challenging societal norms for animal welfare",
    "Vegan activists creating inclusive communities",
    "A powerful documentary exposing the truth about animal industries",
    "Activists using storytelling to inspire change",
    "Vegan advocates working together for a better future",
    "Animal liberation warriors disrupting the status quo",
    "Vegan activists collaborating with environmental movements",
    "Activists celebrating victories for animal rights",
    "Vegan influencers fostering a culture of empathy",
    "A compassionate revolution led by vegan activists"
]

