export const surpriseMePrompts = [
    "Design a playful scene with chickens playing chess",
    "Illustrate a wolf having a picnic with foxes in a meadow",
    "Create a cartoonish depiction of pigs riding skateboards",
    "Visualize a cityscape where cows are the architects of skyscrapers",
    "Craft a scene of geese having a dance party in a barn",
    "Imagine mink and dolphins collaborating on an underwater art project",
    "Design a futuristic space station run by orcas",
    "Create a serene landscape with lambs enjoying a spa day",
    "Illustrate rabbits engaged in a friendly game of soccer",
    "Craft a scene of dogs and cats hosting a movie night",
    "Visualize monkeys and fish creating a vibrant underwater fashion show",
    "Imagine goats having a rock concert on top of a mountain",
    "Design a city where chickens are the chefs of popular restaurants",
    "Create a bustling market scene with pigs as fruit vendors",
    "Illustrate a wolf and foxes operating a hot air balloon ride",
    "Craft a scene of cows participating in a synchronized swimming competition",
    "Visualize geese having a carnival with various games and rides",
    "Imagine mink and dolphins forming a musical orchestra",
    "Design a farm where orcas help harvest crops",
    "Create a scene of lambs practicing yoga in a peaceful meadow",
    "Illustrate rabbits enjoying a day at the beach with surfboards",
    "Craft a serene landscape with dogs and cats meditating",
    "Visualize monkeys and fish running a successful detective agency",
    "Imagine goats hosting a cooking show on television",
    "Design a city where chickens are the star athletes in a sports league",
    "Create a bustling market scene with pigs as flower vendors",
    "Illustrate a wolf and foxes operating a food truck",
    "Craft a scene of cows running a high-tech computer lab",
    "Visualize geese having a talent show with various performances",
    "Imagine mink and dolphins building sandcastles on the beach",
    "Design a farm where orcas help plant and care for vegetables",
    "Create a scene of lambs enjoying a musical concert under the stars",
    "Illustrate rabbits and dogs forming a synchronized swimming team",
    "Craft a serene landscape with cats and monkeys practicing mindfulness",
    "Visualize a playful underwater party with fish and dolphins",
    "Imagine goats and pigs forming a band and playing instruments",
    "Design a city where chickens are expert pilots flying hot air balloons",
    "Create a bustling market scene with rabbits selling handmade crafts",
    "Illustrate a wolf and foxes organizing a community book club",
    "Craft a scene of cows and dogs participating in a dance-off",
    "Visualize geese enjoying a peaceful boat ride on a calm lake",
    "Imagine mink and dolphins collaborating on an underwater research project",
    "Design a farm where orcas help care for an orchard of fruit trees",
    "Create a scene of lambs and rabbits hosting a joint tea party",
    "Illustrate a wolf and foxes operating a bakery together",
    "Craft a serene landscape with dogs and monkeys enjoying a picnic",

]

// export const surpriseMePrompts = [
//     "Animal liberation activists freeing captive animals",
//     "Vegan activists peacefully protesting for change",
//     "Empowered individuals advocating for animal rights",
//     "A powerful vegan demonstration in a bustling city",
//     "Vegan activists using art to convey a powerful message",
//     "Animal liberation march with banners and signs",
//     "Compassionate activists rescuing animals from harm",
//     "Vegan warriors fighting for a cruelty-free world",
//     "A global movement for animal liberation",
//     "Inspirational vegan leaders addressing a crowd",
//     "Activists using social media to promote veganism",
//     "Vegan protesters sharing plant-based facts",
//     "Artistic murals advocating for animal rights",
//     "Animal liberation activists engaging in civil disobedience",
//     "Vegan outreach event spreading awareness",
//     "Empathetic individuals rescuing animals from exploitation",
//     "Activists creating positive change through education",
//     "Vegan advocates speaking up for the voiceless",
//     "A world transformed by vegan activism",
//     "Animal rights activists promoting ethical choices",
//     "Vegan influencers using their platforms for change",
//     "Activists disrupting industries that harm animals",
//     "A peaceful gathering advocating for vegan living",
//     "Vegan activists collaborating for a common cause",
//     "Empowered individuals organizing a vegan festival",
//     "Animal liberation warriors breaking chains of oppression",
//     "Vegan activists raising awareness in the community",
//     "A global call for compassion and veganism",
//     "Activists using technology to advance animal rights",
//     "Vegan advocates inspiring others to join the movement",
//     "Protesters demanding justice for animals",
//     "Animal liberation activists promoting kindness over cruelty",
//     "Vegan activists transforming the narrative on animal agriculture",
//     "Activists creating impactful documentaries for change",
//     "Vegan influencers promoting a plant-based lifestyle",
//     "A wave of compassion sweeping the globe",
//     "Animal rights advocates working towards legislative change",
//     "Vegan activists organizing plant-powered fundraisers",
//     "Activists challenging societal norms for animal welfare",
//     "Vegan activists creating inclusive communities",
//     "A powerful documentary exposing the truth about animal industries",
//     "Activists using storytelling to inspire change",
//     "Vegan advocates working together for a better future",
//     "Animal liberation warriors disrupting the status quo",
//     "Vegan activists collaborating with environmental movements",
//     "Activists celebrating victories for animal rights",
//     "Vegan influencers fostering a culture of empathy",
//     "A compassionate revolution led by vegan activists"
// ]

